## Import libraries:

In [1]:
# import libraries
import pandas as pd
import seaborn as sns 
import matplotlib as plt

# X and Y - Train & Test
from sklearn.model_selection import train_test_split

# Pipeline - Vectorization (Text to Number) - Model Selection - Train Model
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression

# Evaluation - Prediction
from sklearn.metrics import classification_report

# Load Dataset:

In [2]:
df = pd.read_csv('Fake_Real_News_Data.csv')
df.drop(columns="Unnamed: 0",inplace=True)
# df.info()
df.head()
# df.shape

,title,text,label
0,A whirlwind day in D.C. showcases Trump’s unor...,Donald Trump endorsed an unabashedly noninterv...,REAL
1,"In Baltimore's call for federal police probe, ...",While some Justice Department investigations a...,REAL
2,Trump Proudly Declares: Most Of The People I’v...,Trump Proudly Declares: Most Of The People I’v...,FAKE
3,Inside the Trump-Bush melodrama: Decades of te...,Donald Trump spent a day in January 2014 hobno...,REAL
4,Shutdown clash to return in force by December,Notable names include Ray Washburne (Commerce)...,REAL

## Check Missing Values:

In [3]:
# df.isnull().sum()
df.dropna(axis=1)

,title,text,label
0,A whirlwind day in D.C. showcases Trump’s unor...,Donald Trump endorsed an unabashedly noninterv...,REAL
1,"In Baltimore's call for federal police probe, ...",While some Justice Department investigations a...,REAL
2,Trump Proudly Declares: Most Of The People I’v...,Trump Proudly Declares: Most Of The People I’v...,FAKE
3,Inside the Trump-Bush melodrama: Decades of te...,Donald Trump spent a day in January 2014 hobno...,REAL
4,Shutdown clash to return in force by December,Notable names include Ray Washburne (Commerce)...,REAL
...,...,...,...
6330,Obama To Limit Police Acquisition Of Some Mili...,Obama To Limit Police Acquisition Of Some Mili...,REAL
6331,EU using taxpayer money to give Muslim invader...,BNI Store Oct 29 2016 EU using taxpayer money ...,FAKE
6332,Watching These 55 ISIS Terrorists Get Blown to...,Next Story → Judge Judy LOSES IT on Hood Rat: ...,FAKE
6333,America’s Streets Will Run With Blood- Mike Adams,America’s Streets Will Run With Blood- Mike Ad...,FAKE
6334,The immigration swamp,“This was not a subject that was on anybody’s ...,REAL

## Check Duplicate Data:

In [4]:
df.duplicated().sum()
df.drop_duplicates(inplace=True)

## Select X and Y / Train Test Split:

In [5]:
df['Text'] = df['title'] + df['text']

X = df['text']
y = df['label']
xtrain, xtest, ytrain, ytest = train_test_split(X, y, train_size=0.8, random_state=42)

## Check Balanced / Imbalanced:

In [6]:
y.value_counts(normalize=True) * 100

label
REAL    50.015858
FAKE    49.984142
Name: proportion, dtype: float64

## Model Selection / Train Model:

In [7]:
main_pipe = Pipeline (                                          # Text Vectorization
   steps= [
            ('tfidf',TfidfVectorizer()),
            ('model',LogisticRegression(max_iter=1000))
    ]
)

main_pipe.fit(xtrain,ytrain)                                    # Train Model

Pipeline(steps=[('tfidf', TfidfVectorizer()),
                ('model', LogisticRegression(max_iter=1000))])

## Evaluation / Prediction:

In [8]:
print("Train: ")
ytrain_pred = main_pipe.predict(xtrain)
print(classification_report(ytrain,ytrain_pred))

print("test: ")
ytest_pred = main_pipe.predict(xtest)
print(classification_report(ytest,ytest_pred))

Train:
              precision    recall  f1-score   support

        FAKE       0.94      0.96      0.95      2548
        REAL       0.96      0.94      0.95      2496

    accuracy                           0.95      5044
   macro avg       0.95      0.95      0.95      5044
weighted avg       0.95      0.95      0.95      5044

test:
              precision    recall  f1-score   support

        FAKE       0.90      0.94      0.92       604
        REAL       0.94      0.90      0.92       658

    accuracy                           0.92      1262
   macro avg       0.92      0.92      0.92      1262
weighted avg       0.92      0.92      0.92      1262

## Taking Sample Datas:

In [9]:
# df['Text'][0]
# df['Text'][1]
df['Text'][2]

'Trump Proudly Declares: Most Of The People I’ve Insulted Deserved ItTrump Proudly Declares: Most Of The People I’ve Insulted Deserved It By Andrew Bradford on October 27, 2016 Subscribe \nArrogance is defined as “an insulting way of thinking or behaving that comes from believing that you are better, smarter, or more important than other people.” In other words, Donald Trump perfectly exemplifies arrogance, and he just proved that fact yet again. \nAppearing on Good Morning America Thursday morning, the GOP nominee readily defended the insulting posts he’s made on Twitter: “It’s ok, most of them deserved it.” \nTrump then declared : “I believe in fighting back when people are against me, when they tell lies, you know, I have the power of this instrument and frankly sometimes I’ll use that. And I agree sometimes it will revert back or sometimes maybe it doesn’t come out — you have to be careful with it.” \nWhen exactly has Trump been careful with what he posts on social media? Try never. \nMelania Trump, who was also interviewed, said that if she becomes First Lady, one of her primary areas of focus would be social media: “What’s going on is very hurtful to children, to some adults as well.” \nDoes that mean she’ll take away Donald’s cell phone and duct tape his hands to his sides so he can’t tweet out hateful and hurtful shit the way he normally does? Yeah, good luck with that, Melania! \nEarlier this week, the New York Times ran a two-page spread listing all of the insults and unkind postings Trump has made on Twitter since he announced he would be running for President in 2015. If you want to see a completely unhinged, uninformed, and unfiltered mind at work, just take a look at the Times article and recall what Hillary Clinton said regarding the Donald: “A man you can bait with a tweet is not a man we can trust with nuclear weapons.” \nDonald Trump cannot be trusted with a smart phone, let alone the reins of power for the most important nation in the world. \nFeatured Image Via YouTube Screengrab About Andrew Bradford \nAndrew Bradford is a single father who lives in Atlanta. A member of the Christian Left, he has worked in the fields of academia, journalism, and political consulting. His passions are art, music, food, and literature. He believes in equal rights and justice for all. To see what else he likes to write about, check out his blog at Deepleftfield.info. Connect'

## New input Test / Output:

In [10]:
new_input = [
    'A whirlwind day in D.C. showcases Trump’s unorthodox views and shifting toneDonald Trump endorsed an unabashedly noninterventionist approach to world affairs Monday during a day-long tour of Washington, casting doubt on the need for the North Atlantic Treaty Organization and expressing skepticism about a muscular U.S. military presence in Asia.\n\nThe foreign policy positions — outlined in a meeting with the editorial board of The Washington Post — came on a day when Trump set aside the guerrilla tactics and showman bravado that have powered his campaign to appear as a\xa0would-be presidential nominee, explaining his policies, accepting counsel and building bridges to Republican elites.\n\nOn Monday night, Trump delivered a scripted address in front of the American Israel Public Affairs Committee, prompting ovations with pledges to stand by Israel and take a hard line on peace talks with the Palestinians.\n\nTrump’s whirlwind day of appearances around the nation’s capital was intended in part to head off an establishment push to deny him the Republican Party’s nomination. But in the Post meeting, the billionaire mogul also made clear that he would not be beholden to the GOP’s long-held orthodoxies.\n\nDuring the hour-long discussion, during which he revealed five of his foreign policy advisers, Trump advocated a light footprint in the world. In spite of unrest in the Middle East and elsewhere, he said, the United States must look inward and steer its resources toward rebuilding the nation’s crumbling infrastructure.\n\n“At what point do you say, ‘Hey, we have to take care of ourselves?’\u2009” Trump said in the editorial board meeting. “I know the outer world exists, and I’ll be very cognizant of that. But at the same time, our country is disintegrating, large sections of it, especially the inner cities.”\n\nTrump said U.S. involvement in NATO may need to be significantly diminished in the coming years, breaking with nearly seven decades of consensus in Washington. “We certainly can’t afford to do this anymore,” he said, adding later, “NATO is costing us a fortune, and yes, we’re protecting Europe with NATO, but we’re spending a lot of money.”\n\n[A transcript of Donald Trump’s meeting with The Washington Post editorial board]\n\nThroughout his unlikely campaign, Trump’s unpredictable, incendiary persona has been his rocket fuel. But with the nomination now within his reach, he is trying at times to round out his sharp edges to convince his party’s leaders — not to mention general-election voters — that he has the temperament and knowledge to be president.\n\nThis was one of Trump’s goals as he addressed AIPAC’s annual conference in Washington. For perhaps the first time in his campaign, Trump read from a prepared text on teleprompters — a device he has colorfully mocked other politicians for using.\n\nOn Israel, Trump mostly hewed to the party line, giving a full-throated defense of the nation and its interests and arguing that no candidate is a more forceful champion of the Jewish state. His eyes pinging back and forth between the teleprompter screens, Trump embellished his prepared text only to deliver a few criticisms of President Obama and his first-term secretary of state, Hillary Clinton, the Democratic presidential front-runner.\n\n“When I become president, the days of treating Israel like a second-class citizen will end on Day One,” Trump vowed. He received enthusiastic applause from the crowd of thousands, and the much-rumored walkouts during his speech were either called off or went unnoticed in the cavernous Verizon Center arena.\n\nEarlier Monday, Trump sought to cultivate ties with his party’s establishment at a private luncheon he hosted on Capitol Hill. It was attended by about two dozen Republicans, including influential conservatives in Congress and prominent figures from GOP policy and lobbying circles.\n\nThose with whom he met directly urged Trump to “be more presidential,” according to one attendee. This person, who like others spoke on the condition of anonymity to relate details of the closed session, described it as “a very serious conversation,” adding: “This was the Donald Trump who talks with bankers, not the Donald Trump who is on the stage.”\n\nTrump also sought to showcase his business acumen and dealmaking prowess. He staged an afternoon news conference at the historic Old Post Office Pavilion, which his real estate company is turning into a Trump International Hotel, a few blocks from the White House on Pennsylvania Avenue. The candidate, flanked by employees wearing hard hats, led journalists on a tour of the construction zone.\n\nTrump’s visit to Washington comes amid an intensified effort by some in the Republican establishment, including 2012 presidential nominee Mitt Romney, to deny him the nomination by forcing a contested convention at which the party could rally around an alternative.\n\nAt his luncheon meeting, Trump warned party leaders against using parliamentary maneuvers to block his nomination. He later told reporters that he had a productive conversation recently with House Speaker Paul D. Ryan (R-Wis.) and that he has “many millions of people behind me.”\n\n“Now, they can play games, and they can play cute,” Trump said of Ryan and other GOP leaders. “I can only take [Ryan] at face value. I understand duplicity. I understand a lot of things. But he called me last week, he could not have been nicer. I spoke with Mitch McConnell, he could not have been nicer. If people want to be smart, they should embrace this movement.”\n\nNeither Ryan nor McConnell (R-Ky.), the Senate majority leader, attended Monday’s meeting with Trump. It was held at Jones Day, the law firm of Donald F. McGahn, a Trump campaign attorney, and was convened in part by Sen. Jeff Sessions (R-Ala.), a key Trump ally.\n\nAttendees included Heritage Foundation President Jim De\xadMint, a former senator from South Carolina and a conservative movement leader, as well as Sen. Tom Cotton (R-Ark.), former House speaker Newt Gingrich (R-Ga.) and former House Appropriations Committee chairman Bob Livingston (R-La.). A group of House members who have endorsed Trump also attended.\n\n“We met with Senator Sessions and some of the great people in Washington,” Trump said. “We had a really good meeting. .\u2009.\u2009. They can’t believe how far we’ve come because, you know, I think a lot of people maybe wouldn’t have predicted that.”\n\nTrump began the day at The Post, where his on-the-record meeting with the editorial board covered media libel laws, violence at his rallies and climate change, as well as foreign policy.\n\nFor the first time, Trump listed members of a team chaired by Sessions that is counseling him on foreign affairs and helping to shape his policies: Keith Kellogg, Carter Page, George Papadopoulos, Walid Phares and Joseph E. Schmitz. All are relatively little known in foreign policy circles, and several have ties to the George W. Bush administration.\n\nTrump praised George P. Shultz, who served as President Ronald Reagan’s secretary of state, as a model diplomat and, on the subject of Russia’s aggression in Ukraine, said America’s allies are “not doing anything.”\n\n“Ukraine is a country that affects us far less than it affects other countries in NATO, and yet we’re doing all of the lifting,” Trump said. “They’re not doing anything. And I say: ‘Why is it that Germany’s not dealing with NATO on Ukraine? .\u2009.\u2009. Why are we always the one that’s leading, potentially, the third world war with Russia?’\u2009”\n\nWhile the Obama administration has faced pressure from congressional critics who have advocated for a more active U.S. role in supporting Ukraine, the U.S. military has limited its assistance to nonlethal equipment such as vehicles and night-vision gear. European nations have taken the lead in crafting a fragile cease-fire designed to decrease hostility between Ukrainian forces and Russian-backed separatists.\n\nTrump sounded a similar note in discussing the U.S. presence in the Pacific. He questioned the value of massive military investments in Asia and wondered aloud whether the United States still is capable of being an effective peacekeeping force there.\n\n“South Korea is very rich, great industrial country, and yet we’re not reimbursed fairly for what we do,” Trump said. “We’re constantly sending our ships, sending our planes, doing our war games — we’re reimbursed a fraction of what this is all costing.”\n\nSuch talk is likely to trigger anxiety in South Korea, where a U.S. force of 28,000 has provided a strong deterrent to North Korean threats for decades.\n\nAsked whether the United States benefits from its involvement in Asia, Trump replied, “Personally, I don’t think so.” He added: “I think we were a very powerful, very wealthy country. And we’re a poor country now. We’re a debtor nation.”\n\nJenna Johnson, Paul Kane, Missy Ryan and David Weigel contributed to this report.',
    'In Baltimore\'s call for federal police probe, a new search for answers (+video)While some Justice Department investigations are adversarial, a new model of collaborative reform is surprising police in some cities, as\xa0they find themselves included as part of the solution.\n\nSearching for a "framework ... [to] heal," Baltimore Mayor Stephanie Rawlings-Blake put in a 911 call to the US Department of Justice to ask for a civil rights investigation into the Baltimore Police Department’s beat cop tactics.\n\nHer call, not even a week after a local prosecutor charged six police officers with crimes including murder for their alleged role in the death of Freddie Gray, is part of a broader trend of "collaborative reform" between Washington and local jurisdictions.\n\nWhat\'s striking about such investigations is that they don\'t just slam the police, but also aim to help officers stay safe and protect citizens, as well as show that they are part of the solution.\n\nIn fact, following a Baltimore Sun series on police abuses in the city last year, Police Commissioner Anthony Batts approached the Justice Department to conduct a collaborative review, which had been under way the day Mr. Gray died while in police custody.\n\nSome DOJ investigations are adversarial, as police bristle at court orders and federal monitors. But a federal investigation into whether Baltimore cops routinely violate people’s civil rights is likely to mirror similar probes in Las Vegas and Philadelphia, where police chiefs have been able to use federal findings to gain leverage with elected officials and also use facts to rebut claims by police officers that they’re doing nothing wrong, says Sam Walker, a criminologist at the University of Nebraska at Omaha.\n\nTo be sure, Mr. Walker says, it’s “too early to tell” whether such interventions can bring the kind of fundamental reforms that Mayor Rawlings-Blake is hoping to find in the aftermath of Gray’s death and injuries to nearly 100 cops during violent riots.\n\nBut there is growing evidence that such collaborative efforts can help communities grapple with deep tensions between police and neighborhoods and build trust around common goals like respect, dignity, and sanctity of life.\n\nAfter Las Vegas police shot a record 25 people in 2010, the city began its own reforms and asked the Department of Justice for help a year later. In 2011, the DOJ began the new collaboration program, delving deep into practices, training procedures, and policies to root out where officers were going wrong and where policies failed the people.\n\nAs of 2012, the Las Vegas department had completed dozens of difficult reforms, including rewriting its use-of-deadly-force policy to include a reference to officers acknowledging the “sanctity of human life” as they make critical split-second decisions. The department added so-called reality-based training to give officers more options than quick deployment of deadly force as they interacted with drugged, drunk, or mentally ill citizens. Since then, the number of officer-involved shootings in Las Vegas has stayed below historical averages, year to year.\n\nIn March, the Justice Department reported back on practices of the Philadelphia Police Department, which had seen a stretch of years in which police killed a person nearly every week, many of them unarmed. The DOJ team, which was made up of policing experts and not prosecutors, released a string of findings that pointed to problems in both policy and training.\n\nSurprisingly to some, many complaints came from officers themselves. Among the findings were complaints from officers that they were not properly trained to deal with violent suspects. The training needed to be less staged and more reality-based, officers said, including allowing trainees to grapple with each other to learn tactics.\n\n“Interview participants generally thought that the defensive tactics training offered at the academy focused too much on legal liability and not enough on teaching practical and realistic methods for surviving a physical encounter,” the DOJ report stated. “They did not believe that [training] sufficiently prepared them for a physical encounter.”\n\nAside from giving leaders hard facts to work with, such reports can also help defend police officers. Even though many police shootings have a racial backdrop, the Justice Department found that Philadelphia police did not have a problem with racial stereotyping. In fact, unarmed white males were more likely to be shot and killed by Philadelphia police than unarmed black males.\n\n“I want to express regrets for all who have been shot in Philadelphia, civilians or police officers.... Every life is precious in this city and this country, so we need to maintain this level of focus," Philadelphia Mayor Michael Nutter said in March. "We\'re one big city. Everyone wants to be safe. Citizens want to be safe. Police officers want to be safe."\n\nThe Justice Department has conducted 19 civil rights investigations since 2000, stepping up the efforts in the Obama era, with five police departments coming under federal monitoring in 2012 alone. Some of those investigations have been scathing, including a report in March that documented abuses by the Ferguson (Mo.) Police Department that helped fuel protests in the wake of Michael’s Brown death last August, at the hands of a police officer.\n\nSo far, Attorney General Loretta Lynch has not replied to the Baltimore mayor’s request for a separate civil rights abuse probe.\n\nBut the request makes clear that the city’s police probably have problems that go beyond the treatment of Gray.\n\nSince 2011, the city has settled more than 100 lawsuits equaling nearly $6 million in cases where people were bruised and battered by officers, only to have trumped-up charges later dropped by a judge.\n\nTrue, institutional change can be difficult. After the Baltimore Police Department promised the courts in 2010 it would curb the large percentage of false arrests in the city by offering better training, the department dragged its feet, the American Civil Liberties Union has alleged. The issue has reared up again in the Gray case, since prosecutor Marilyn Mosby has charged that officers falsely arrested Gray for carrying a legal knife.\n\nBut so far in Philadelphia and Las Vegas, one key to success has been the efforts to engage police officers in the process by showing them that they are part of the solution, and that the collaboration isn\'t about outsiders second-guessing their actions. In Philadelphia, Commissioner Charles Ramsey sent every officer a link to the Las Vegas report, so they could see for themselves that it was more an attempt to help officers stay safe and protect citizens than blaming them for their actions.\n\n"Cops are always leery of something," Mr. Ramsey told the Baltimore Sun. "We did as much as we could to alleviate any concerns and fears."',
    'Trump Proudly Declares: Most Of The People I’ve Insulted Deserved ItTrump Proudly Declares: Most Of The People I’ve Insulted Deserved It By Andrew Bradford on October 27, 2016 Subscribe \nArrogance is defined as “an insulting way of thinking or behaving that comes from believing that you are better, smarter, or more important than other people.” In other words, Donald Trump perfectly exemplifies arrogance, and he just proved that fact yet again. \nAppearing on Good Morning America Thursday morning, the GOP nominee readily defended the insulting posts he’s made on Twitter: “It’s ok, most of them deserved it.” \nTrump then declared : “I believe in fighting back when people are against me, when they tell lies, you know, I have the power of this instrument and frankly sometimes I’ll use that. And I agree sometimes it will revert back or sometimes maybe it doesn’t come out — you have to be careful with it.” \nWhen exactly has Trump been careful with what he posts on social media? Try never. \nMelania Trump, who was also interviewed, said that if she becomes First Lady, one of her primary areas of focus would be social media: “What’s going on is very hurtful to children, to some adults as well.” \nDoes that mean she’ll take away Donald’s cell phone and duct tape his hands to his sides so he can’t tweet out hateful and hurtful shit the way he normally does? Yeah, good luck with that, Melania! \nEarlier this week, the New York Times ran a two-page spread listing all of the insults and unkind postings Trump has made on Twitter since he announced he would be running for President in 2015. If you want to see a completely unhinged, uninformed, and unfiltered mind at work, just take a look at the Times article and recall what Hillary Clinton said regarding the Donald: “A man you can bait with a tweet is not a man we can trust with nuclear weapons.” \nDonald Trump cannot be trusted with a smart phone, let alone the reins of power for the most important nation in the world. \nFeatured Image Via YouTube Screengrab About Andrew Bradford \nAndrew Bradford is a single father who lives in Atlanta. A member of the Christian Left, he has worked in the fields of academia, journalism, and political consulting. His passions are art, music, food, and literature. He believes in equal rights and justice for all. To see what else he likes to write about, check out his blog at Deepleftfield.info. Connect'
]

result = main_pipe.predict(new_input)
print(result)

['REAL' 'REAL' 'FAKE']